export default {
    BACKGROUND_COLOR: '#FFFFFF',
    PRIMARY_COLOR: '#BFCBD8',
    PRIMARY_COLOR_OPACITY_16: '#BFCBD829',
    PRIMARY_COLOR_OPACITY_12: '#BFCBD81F',
    SECONDARY_COLOR: '#0B7E52',
    TOAST_SUCCESS_COLOR: '#36A41D',
    TOAST_ERROR_COLOR: '#EE3939',
    TOAST_INFO_COLOR: '#1B90FE',
    SPINNER_COLOR: '#006941',
  };
  
  
  